logging.level:
  com.slack.api: DEBUG
server:
  port: 3000
rtm:
  url: https://slack.com/api/rtm.start?token={token}&simple_latest&no_unreads
slack:
  signing.secret: replaceWithOwnSecret
  bot.token: replaceWithOwnBotToken